### ISSUE TITLE
Portworx Enterprise - 3.0.2 Release

### ISSUE THREAD

**Issue by Balachandar-Pan** [IBM/signoff-pxe#2]
- [x] Portworx Enterprise Testing from Portworx Team
- [ ]  Torpedo Test from IBM Cloud Team

**Comment by Balachandar-Pan** [comment]
PX-Enterprise 3.0.2 release notes
https://docs.portworx.com/release-notes/portworx-enterprise#302

Test results of Test catalog from test rail attached
[IBM Marketplace - TestRail PX 3.0.2.pdf](https://github.com/IBM/signoff-pxe/files/12913784/IBM.Marketplace.-.TestRail.PX.3.0.2.pdf)

Note: 
we have filed PWX-34245 for internal issue related to licensing. we did make sure Installation PX 3.0 from Production catalog and updated PX 3.0.2. we are good with licensing and metering on prod catalog.

**Comment by bhargaviSurineedi** [comment]
Test Results 
`surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % kubectl get pods -n kube-system -o wide | grep portworx
portworx-api-2pkcm                          1/1     Running     0          44m     10.240.0.16      10.240.0.16     <none>           <none>
portworx-api-9t4mp                          1/1     Running     0          44m     10.240.128.16    10.240.128.16   <none>           <none>
portworx-api-nwzwz                          1/1     Running     1          44m     10.240.64.23     10.240.64.23    <none>           <none>
portworx-kvdb-6fjk5                         1/1     Running     0          5m27s   10.240.0.16      10.240.0.16     <none>           <none>
portworx-kvdb-h48vh                         1/1     Running     0          2m59s   10.240.128.16    10.240.128.16   <none>           <none>
portworx-kvdb-rc5k2                         1/1     Running     0          3m30s   10.240.64.23     10.240.64.23    <none>           <none>
portworx-mr26z                              1/1     Running     0          11m     10.240.0.16      10.240.0.16     <none>           <none>
portworx-operator-6447f7968d-rgzkl          1/1     Running     0          45m     172.17.210.38    10.240.128.16   <none>           <none>
portworx-pvc-controller-7b6bf56d46-h6jk4    1/1     Running     1          45m     10.240.64.23     10.240.64.23    <none>           <none>
portworx-pvc-controller-7b6bf56d46-m42cn    1/1     Running     0          45m     10.240.128.16    10.240.128.16   <none>           <none>
portworx-pvc-controller-7b6bf56d46-x5t57    1/1     Running     0          45m     10.240.0.16      10.240.0.16     <none>           <none>
portworx-q4l44                              1/1     Running     1          11m     10.240.64.23     10.240.64.23    <none>           <none>
portworx-wl42v                              1/1     Running     0          11m     10.240.128.16    10.240.128.16   <none>           <none>
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % 
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % 
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % 
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % 
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % kubectl get storagecluster -n kube-system
NAME       CLUSTER UUID                           STATUS    VERSION   AGE
portworx   cb78ca9d-756e-499d-95a4-41b7f5b3a4c0   Running   3.0.2     47m
surineedisatyabhargavi@Surineedis-MacBook-Pro-2 bases % 
`

**Comment by Balachandar-Pan** [comment]
Agreed and production catalog updated
