### ISSUE TITLE
Portworx Enterprise - 3.0.4 Release

### ISSUE THREAD

**Issue by Balachandar-Pan** [IBM/signoff-pxe#5]
- [x]  Portworx Enterprise Testing from Portworx Team
- [x]  Torpedo Test from IBM Cloud Team

**Comment by Balachandar-Pan** [comment]
PX-Enterprise 3.0.4 release notes
https://docs.portworx.com/release-notes/portworx-enterprise#304

Test results of Test catalog from test rail attached
[IBM Marketplace - TestRail PX 3.0.4.pdf](https://github.com/IBM/signoff-pxe/files/13498742/IBM.Marketplace.-.TestRail.PX.3.0.4.pdf)

what's new on catalog
PX operator 23.10.1
PX enterprise 3.0.4
Stork 23.8.0

**Comment by bhargaviSurineedi** [comment]
Tested stage catalog 
```surineedisatyabhargavi@Surineedis-MacBook-Pro-2 alchemy-containers % kubectl get storagecluster -n kube-system
NAME       CLUSTER UUID                           STATUS    VERSION   AGE
portworx   90a23826-8244-4ed1-914b-20e5970bcdcb   Running   3.0.4     81m

**Comment by Balachandar-Pan** [comment]
Test catalog validation is completed also updated in prod catalog as well.
